import { test, expect, type Page } from '@playwright/test';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { newLevel } from '../src/world/level';
import { floor, object, exampleProject } from '../src/world/examples';
import type { Vec3 } from '../src/world/types';
const errors = new WeakMap<Page,string[]>();
const snapshot=(page:Page)=>page.evaluate(()=>{const q=(window as any).waterWorkshop;return{level:q.level,state:q.state,water:q.water,settings:q.settings,camera:q.camera,project:q.project};});
const point=(page:Page,p:Vec3)=>page.evaluate(p=>(window as any).waterWorkshop.projectPoint(p),p);
async function clickWorld(page:Page,p:Vec3,button:'left'|'right'|'middle'='left'){const pos=await point(page,p);await page.mouse.click(pos.x,pos.y,{button});await page.waitForTimeout(80);}
async function waitIdle(page:Page){await page.waitForFunction(()=>!(window as any).waterWorkshop.busy);}
test.beforeEach(async({page})=>{const list:string[]=[];errors.set(page,list);page.on('pageerror',e=>list.push(e.message));page.on('console',m=>{if(m.type()==='error')list.push(m.text());});await page.goto('/');await page.waitForFunction(()=>!!(window as any).waterWorkshop);await expect(page.locator('#render-error')).toBeHidden();});
test.afterEach(async({page})=>{expect(errors.get(page)).toEqual([]);});
test('composition, responsive editor, all angles and two verified routes',async({page},info)=>{
  await mkdir('docs/screenshots/phase3',{recursive:true});await page.waitForTimeout(1000);await page.screenshot({path:`docs/screenshots/phase3/${info.project.name}-editor-1920.png`});
  for(const view of ['north','top']as const){await page.locator(`[data-view="${view}"]`).click();await page.waitForTimeout(150);await page.screenshot({path:`docs/screenshots/phase3/${info.project.name}-${view}.png`});}
  await page.locator('#camera-reset').click();await page.setViewportSize({width:1366,height:768});await page.waitForTimeout(200);await page.screenshot({path:`docs/screenshots/phase3/${info.project.name}-editor-1366.png`});
  for(const id of ['play','undo','redo','export','new-chapter','layer','brush'])await expect(page.locator('#'+id)).toBeInViewport();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  for(const id of ['validation-push','validation-pull']){await page.evaluate(id=>(window as any).waterWorkshop.select(id),id);const before=(await snapshot(page)).level;await page.locator('#play').click();for(const command of before.route){await page.evaluate(c=>(window as any).waterWorkshop.act(c),command);await waitIdle(page);}expect((await snapshot(page)).state.status).toBe('won');await expect(page.locator('#win')).toBeVisible();await page.screenshot({path:`docs/screenshots/phase3/${info.project.name}-${id}-win.png`});await page.locator('#undo').click();expect((await snapshot(page)).state.status).toBe('playing');await page.locator('#redo').click();expect((await snapshot(page)).state.status).toBe('won');await page.locator('#restart').click();expect((await snapshot(page)).state.turn).toBe(0);await page.locator('#play').click();expect((await snapshot(page)).level).toEqual(before);}
});
test('chapter workflow and real mouse stacking, rectangle, delete and sampling',async({page})=>{
  await page.locator('#new-chapter').click();await page.locator('#name-input').fill('验收章节');await page.locator('#name-form button[type=submit]').click();
  const chapter=page.locator('.chapter').filter({hasText:'验收章节'});await chapter.locator('.new-level').click();await page.locator('#name-input').fill('建造流程');await page.locator('#name-form button[type=submit]').click();
  await page.locator('[data-view=top]').click();await page.locator('#rectangle').check();const a=await point(page,{x:3,y:0,z:3}),b=await point(page,{x:7,y:0,z:7});await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:8});await page.mouse.up();expect((await snapshot(page)).level.objects).toHaveLength(25);
  await page.locator('#undo').click();expect((await snapshot(page)).level.objects).toHaveLength(0);await page.locator('#redo').click();await page.locator('#rectangle').uncheck();
  await clickWorld(page,{x:4,y:1,z:4});await clickWorld(page,{x:4,y:2,z:4});expect((await snapshot(page)).level.objects.filter((o:any)=>o.x===4&&o.z===4)).toHaveLength(3);
  // One held brush erases only the initial front object, even while the exposed lower surface changes.
  const p=await point(page,{x:4,y:3,z:4});await page.mouse.move(p.x,p.y);await page.mouse.down({button:'right'});await page.mouse.move(p.x+1,p.y+1,{steps:8});await page.mouse.move(p.x,p.y,{steps:8});await page.mouse.up({button:'right'});expect((await snapshot(page)).level.objects.filter((o:any)=>o.x===4&&o.z===4)).toHaveLength(2);await page.locator('#undo').click();
  await page.locator('[data-tool=crate]').click();await clickWorld(page,{x:6,y:1,z:6});await page.locator('[data-tool=stone]').click();const camera=(await snapshot(page)).camera;await clickWorld(page,{x:6,y:2,z:6},'middle');expect((await snapshot(page)).settings.tool).toBe('crate');expect((await snapshot(page)).camera).toEqual(camera);
  const c=await point(page,{x:5,y:1,z:5});await page.mouse.move(c.x,c.y);await page.mouse.down({button:'middle'});await page.mouse.move(c.x+100,c.y+60,{steps:10});await page.mouse.up({button:'middle'});expect((await snapshot(page)).camera).not.toEqual(camera);expect((await snapshot(page)).settings.tool).toBe('crate');
  await page.locator('[data-view=top]').click();await page.locator('[data-tool=bridge]').click();await page.locator('#layer').fill('3');await page.locator('#layer').press('Tab');await clickWorld(page,{x:8,y:3,z:5});expect((await snapshot(page)).level.objects.some((o:any)=>o.kind==='bridge'&&o.y===3)).toBe(true);
  await page.locator('[data-tool=glass]').click();await clickWorld(page,{x:5,y:1,z:3});await page.locator('[data-tool=source]').click();await clickWorld(page,{x:3,y:1,z:4});await page.locator('[data-tool=spawn]').click();await clickWorld(page,{x:3,y:1,z:6});
  const draft=(await snapshot(page)).level;await page.locator('#play').click();expect((await snapshot(page)).state).not.toBeNull();await page.keyboard.press('d');await waitIdle(page);await page.locator('#play').click();expect((await snapshot(page)).level).toEqual(draft);await page.locator('#save').click();await expect(page.locator('#save-state')).toHaveText('已自动保存');await page.reload();await page.waitForFunction(()=>!!(window as any).waterWorkshop);expect((await snapshot(page)).level).toEqual(draft);
});
test('JSON round trip, import rejection, chapter copies and recoverable deletion',async({page})=>{
  const before=(await snapshot(page)).level;await page.locator('#file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":3}')});await expect(page.locator('#notice')).toContainText('导入失败');expect((await snapshot(page)).level).toEqual(before);
  const download=page.waitForEvent('download');await page.locator('#export').click();const path=(await(await download).path())!;const raw=await readFile(path,'utf8');expect(JSON.parse(raw)).toEqual(before);await page.locator('#file').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(raw)});await expect(page.locator('#notice')).toContainText('导入成功');const copy=(await snapshot(page)).level;expect(copy.id).not.toBe(before.id);expect({...copy,id:before.id}).toEqual(before);
  await page.locator('#delete-level').click();await page.locator('#trash').click();await page.locator('[data-recover]').last().click();await page.locator('#trash-close').click();expect((await snapshot(page)).level).toEqual(copy);
});
test('slice is visual only, collision previews and 3 by 3 brush',async({page})=>{
  const l=newLevel('剖视试验');floor(l,0,3,3,7,7);floor(l,4,3,3,7,7);l.source={x:4,y:5,z:4};l.spawn={x:5,y:5,z:5};await page.evaluate(l=>(window as any).waterWorkshop.setLevel(l),l);const before=(await snapshot(page)).water;await page.locator('#slice').fill('1');await page.locator('#slice').press('Tab');expect((await snapshot(page)).water).toEqual(before);
  await page.locator('[data-view=top]').click();await page.locator('#brush').selectOption('3');await clickWorld(page,{x:5,y:1,z:5});expect((await snapshot(page)).level.objects.filter((o:any)=>o.y===1)).toHaveLength(9);await page.locator('#undo').click();expect((await snapshot(page)).level).toEqual(l);
});
test('reduced motion, single buffered command and independent rule history',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'});await page.reload();await page.waitForFunction(()=>!!(window as any).waterWorkshop);await expect(page.locator('#pause')).toHaveText('播放水面');await page.locator('#play').click();const before=(await snapshot(page)).state;await page.keyboard.press('s');expect((await snapshot(page)).state.turn).toBe(1);expect(await page.evaluate(()=>(window as any).waterWorkshop.busy)).toBe(true);await page.locator('#undo').click();expect((await snapshot(page)).state).toEqual(before);await waitIdle(page);
  await page.emulateMedia({reducedMotion:'no-preference'});await page.evaluate(()=>{const q=(window as any).waterWorkshop;q.act({type:'move',direction:'south'});for(let i=0;i<20;i++)q.act({type:'wait'});});await waitIdle(page);expect((await snapshot(page)).state.turn).toBe(2);await page.locator('#restart').click();expect((await snapshot(page)).state).toEqual(before);
});
test('storage failures retain memory and exports',async({page})=>{
  await page.evaluate(()=>{IDBFactory.prototype.open=function(){throw new DOMException('模拟存储失败','QuotaExceededError');};});await page.locator('#rename-level').click();await page.locator('#name-input').fill('依然保留的草稿');await page.locator('#name-form button[type=submit]').click();await page.locator('#save').click();await expect(page.locator('#save-state')).toHaveText('仅保存在本页');expect((await snapshot(page)).level.name).toBe('依然保留的草稿');const download=page.waitForEvent('download');await page.locator('#export').click();expect((await download).suggestedFilename()).toContain('依然保留的草稿');
});
test('32 by 32 maximum footprint and multilayer performance',async({page,browser},info)=>{
  const l=newLevel('32 × 32 多层庭院',32,32);floor(l);floor(l,4);l.source={x:16,y:5,z:16};l.spawn={x:14,y:5,z:14};for(let x=0;x<32;x++)object(l,'glass',x,5,0);const times=await page.evaluate(l=>{const q=(window as any).waterWorkshop;const start=performance.now();q.setLevel(l);return performance.now()-start;},l);await page.waitForTimeout(700);
  const samples:number[]=[];for(let i=0;i<4;i++){await page.waitForTimeout(1000);samples.push(await page.evaluate(()=>(window as any).waterWorkshop.fps));}
  await writeFile(`docs/phase3-${info.project.name}-performance.json`,JSON.stringify({browser:browser.version(),viewport:page.viewportSize(),objects:l.objects.length,loadAndSolveMs:times,fps:samples},null,2));expect((await snapshot(page)).water.cells.length).toBe(2048);await page.screenshot({path:`docs/screenshots/phase3/${info.project.name}-maximum.png`});
});
test('art and boat animation views',async({page},info)=>{
  const p=exampleProject();for(const name of ['桥下的水路','浮船与永久载荷','隔水牵引','落水的力量']){await page.evaluate(id=>(window as any).waterWorkshop.select(id),`sample-${name}`);await page.locator('#play').click();await page.waitForTimeout(500);await page.screenshot({path:`docs/screenshots/phase3/${info.project.name}-${name}.png`});expect((await snapshot(page)).state).not.toBeNull();await page.locator('#play').click();}expect(Object.keys(p.levels)).toHaveLength(12);
});
test('full 32-layer volume, cutaway and response benchmark',async({page,browser},info)=>{
  const l=newLevel('32 层压力场景',32,32);for(let y=0;y<32;y++)floor(l,y);l.source={x:16,y:32,z:16};l.spawn={x:14,y:32,z:14};
  const start=Date.now();await page.evaluate(l=>(window as any).waterWorkshop.setLevel(l),l);const loadMs=Date.now()-start,timings=await page.evaluate(()=>(window as any).waterWorkshop.timings);await page.waitForTimeout(1500);const fps:number[]=[];for(let i=0;i<3;i++){await page.waitForTimeout(1000);fps.push(await page.evaluate(()=>(window as any).waterWorkshop.fps));}
  const before=(await snapshot(page)).water;await page.locator('#slice').fill('15');await page.locator('#slice').press('Tab');expect((await snapshot(page)).water).toEqual(before);await page.locator('[data-view=top]').click();await clickWorld(page,{x:15,y:16,z:15},'right');expect((await snapshot(page)).level.objects).toHaveLength(32767);await page.locator('#undo').click();expect((await snapshot(page)).level.objects).toHaveLength(32768);
  await writeFile(`docs/phase3-${info.project.name}-volume-performance.json`,JSON.stringify({browser:browser.version(),viewport:page.viewportSize(),objects:32768,loadRoundTripMs:loadMs,timings,fps},null,2));
});
test('V1 local draft migration keeps original and IndexedDB backup',async({page})=>{
  const legacy={version:1,name:'旧草稿验收',width:4,depth:4,terrain:Array.from({length:4},()=>Array(4).fill(0)),source:{x:0,z:0},spawn:{x:1,z:1},boxes:[],decorations:[]};
  await page.evaluate(l=>localStorage.setItem('water-paradise:editor:v1',JSON.stringify(l)),legacy);await page.reload();await page.waitForFunction(()=>!!(window as any).waterWorkshop);expect((await snapshot(page)).level.name).toBe('旧草稿验收');expect((await snapshot(page)).level.objects).toHaveLength(16);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('water-paradise:editor:v1')!).version)).toBe(1);
  await page.reload();await page.waitForFunction(()=>!!(window as any).waterWorkshop);expect((await snapshot(page)).project.chapters.filter((c:any)=>c.name==='旧版草稿 · 已迁移')).toHaveLength(1);
});
test('complete chapter import is atomic and preserves all levels',async({page})=>{
  const before=(await snapshot(page)).project;await page.evaluate(text=>(window as any).waterWorkshop.importJSON(text),JSON.stringify(before));const next=(await snapshot(page)).project;expect(Object.keys(next.levels)).toHaveLength(24);expect(next.chapters).toHaveLength(6);
  await page.locator('#file').setInputFiles({name:'bad-project.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...before,levels:{}}))});await expect(page.locator('#notice')).toContainText('导入失败');expect((await snapshot(page)).project.chapters).toEqual(next.chapters);
});
test('blocked storage and unavailable WebGL retain readable errors and export',async({browser,baseURL})=>{
  const context=await browser.newContext();await context.addInitScript(()=>{Object.defineProperty(window,'indexedDB',{get(){throw new DOMException('Denied','SecurityError');}});const original=HTMLCanvasElement.prototype.getContext;(HTMLCanvasElement.prototype as any).getContext=function(type:string,...args:any[]){return type==='webgl2'?null:(original as any).call(this,type,...args);};});const page=await context.newPage(),unhandled:string[]=[];page.on('pageerror',e=>unhandled.push(e.message));await page.goto(baseURL!+'/');await expect(page.locator('#render-error')).toBeVisible();await expect(page.locator('#loading')).toBeHidden();await expect(page.locator('#export')).toBeEnabled();expect(unhandled).toEqual([]);await context.close();
});
